version: '3.8'

services:
#  postgres:
#    image: postgres:15
#    container_name: postgres_container
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: monit
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    restart: always # Reinicia automáticamente el contenedor si se detiene

  redis:
    image: redis:7.2
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:

